substitutions:
  name: "everything-presence-one"
  friendly_name: "Everything Presence One"
  project_name: "Everything Smart Technology.Everything Presence One"
  project_version: "1.2.10"
  temperature_offset: "-3"
  humidity_offset: "5"
  temperature_update_interval: "60s"
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  factory_reset_disabled: "true"
  uart_target_output_disabled: "true"
  uart_presence_output_disabled: "true"
  log_level: "ERROR"

update:
  - platform: http_request
    id: update_http_request
    name: Everything Presence One Firmware
    source: https://everythingsmarthome.github.io/everything-presence-one/everything-presence-one-ha-sen0395-co2-ble-rev1-5-stable-manifest.json
    disabled_by_default: true

dashboard_import:
  package_import_url: github://everythingsmarthome/everything-presence-one/everything-presence-one-ble-co2.yaml@main
  import_full_config: false

packages:
  device_base: !include common/everything-presence-one-base.yaml
  device_version: !include common/everything-presence-one-sen0395-stable.yaml
  bluetooth_base: !include common/bluetooth-base.yaml
  sen0395_base: !include common/sen0395-common.yaml
  co2_base: !include common/modules/co2-rev1.5.yaml